# Use root/example as user/password credentials
version: '3.1'
services:
######################################################
# DATABASE SERVICE
######################################################

  db:
    build: ./docker/mysql
    container_name: sparkmysql
    image: mysql
    restart: always
    ports:
      - "3308:3306"
    volumes:
      - ./src/docker/mysql/config/my.cnf:/opt/docker/mysql/config/my.cnf
      - ./src/docker/mysql/config/conf.d/docker.cnf:/opt/docker/mysql/config/conf.d/docker.cnf
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
